export interface FieldConfig {
  type: string;
  label: string;
  placeholder: string;
  className: string;
}

export const formConfig: { [key: string]: FieldConfig } = {
  address: {
    type: "text",
    label: "Recipient Address",
    placeholder: "0xethiring",
    className: "",
  },
  benefits: {
    type: "text",
    label: "Perks & Benefits",
    placeholder: "Unlimited snacks to keep your belly happy!",
    className: "h-11 px-4 border rounded-md",
  },
  bonusAmount: {
    type: "number",
    label: "Bonus Amount (RM)",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  companyPropertyReturn: {
    type: "text",
    label: "Company Property Return",
    placeholder: "Magical office keys and cards",
    className: "h-11 px-4 border rounded-md",
  },
  completionDate: {
    type: "date",
    label: "Completion Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  contractEndDate: {
    type: "date",
    label: "Contract End Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  currentSalary: {
    type: "number",
    label: "Current Annual Salary (RM)",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  department: {
    type: "text",
    label: "Department",
    placeholder: "Human Resource",
    className: "h-11 px-4 border rounded-md",
  },
  effectiveDate: {
    type: "date",
    label: "Effective Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  employmentConfirmation: {
    type: "text",
    label: "Employment Confirmation",
    placeholder: "Confirmed",
    className: "h-11 px-4 border rounded-md",
  },
  employmentEndDate: {
    type: "date",
    label: "Employment End Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  employmentStartDate: {
    type: "date",
    label: "Employment Start Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  employmentStatus: {
    type: "text",
    label: "Employment Status",
    placeholder: "Internship",
    className: "h-11 px-4 border rounded-md",
  },
  expectedImprovements: {
    type: "text",
    label: "Expected Improvements",
    placeholder: "Pay more attention",
    className: "h-11 px-4 border rounded-md",
  },
  expiry: {
    type: "date",
    label: "Package Expiry Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  fullName: {
    type: "text",
    label: "Recipient Full Name",
    placeholder: "John Doe",
    className: "h-11 px-4 border rounded-md",
  },
  issueDate: {
    type: "date",
    label: "Issue Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  issueDescription: {
    type: "text",
    label: "Issue Description",
    placeholder: "Stop eating in the office",
    className: "h-11 px-4 border rounded-md",
  },
  lastWorkingDate: {
    type: "date",
    label: "Last Working Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  leaveEndDate: {
    type: "date",
    label: "Leave End Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  leaveStartDate: {
    type: "date",
    label: "Leave Start Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  leaveType: {
    type: "text",
    label: "Leave Type",
    placeholder: "Annual leave",
    className: "h-11 px-4 border rounded-md",
  },
  newBenefits: {
    type: "text",
    label: "New Benefits",
    placeholder: "Unlimited joy to keep your life happy!",
    className: "h-11 px-4 border rounded-md",
  },
  newDepartment: {
    type: "text",
    label: "New Department",
    placeholder: "IT",
    className: "h-11 px-4 border rounded-md",
  },
  newLocation: {
    type: "text",
    label: "New Location",
    placeholder: "Singapore",
    className: "h-11 px-4 border rounded-md",
  },
  newPosition: {
    type: "text",
    label: "New Position",
    placeholder: "Senior Software Engineer",
    className: "h-11 px-4 border rounded-md",
  },
  newResponsibilities: {
    type: "text",
    label: "New Responsibilities",
    placeholder: "Enjoy more coffee",
    className: "h-11 px-4 border rounded-md",
  },
  newSalary: {
    type: "number",
    label: "New Annual Salary (RM)",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  newTerms: {
    type: "text",
    label: "New Terms",
    placeholder: "No more coffee, just tea from now on",
    className: "h-11 px-4 border rounded-md",
  },
  nonImprovementConsequences: {
    type: "text",
    label: "Non-ImprovementConsequences",
    placeholder: "No lunch break for you",
    className: "h-11 px-4 border rounded-md",
  },
  performanceExpectations: {
    type: "text",
    label: "Performance Expectations",
    placeholder: "Able to complete tasks given before due",
    className: "h-11 px-4 border rounded-md",
  },
  performanceSummary: {
    type: "text",
    label: "Performance Summary",
    placeholder: "Very hardworking",
    className: "h-11 px-4 border rounded-md",
  },
  position: {
    type: "text",
    label: "Position",
    placeholder: "HR Director",
    className: "h-11 px-4 border rounded-md",
  },
  previousWarnings: {
    type: "text",
    label: "Previous Warning",
    placeholder: "Sleeping during working hour",
    className: "h-11 px-4 border rounded-md",
  },
  probationEndDate: {
    type: "date",
    label: "Probation End Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  reason: {
    type: "text",
    label: "Reason",
    placeholder: "My dog ate my homework",
    className: "h-11 px-4 border rounded-md",
  },
  relocationAssistanceDetails: {
    type: "text",
    label: "Relocation Assistance Details",
    placeholder: "Reimbursement for travel expenses",
    className: "h-11 px-4 border rounded-md",
  },
  renewalEndDate: {
    type: "date",
    label: "Renewal End Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  renewalStartDate: {
    type: "date",
    label: "Renewal Start Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  resignationDate: {
    type: "date",
    label: "Resignation Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  responsibilities: {
    type: "text",
    label: "Responsibilities",
    placeholder: "Enjoy coffee",
    className: "h-11 px-4 border rounded-md",
  },
  retirementBenefits: {
    type: "text",
    label: "Retirement Benefits",
    placeholder: "One box of durians",
    className: "h-11 px-4 border rounded-md",
  },
  retirementDate: {
    type: "date",
    label: "Retirement Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  salary: {
    type: "number",
    label: "Annual Salary (RM)",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  severanceDetails: {
    type: "text",
    label: "Severance Details",
    placeholder: "Your last paycheck, with all the trimmings",
    className: "h-11 px-4 border rounded-md",
  },
  skills: {
    type: "text",
    label: "Skills endorsed",
    placeholder: "Java concurrency developer",
    className: "h-11 px-4 border rounded-md",
  },
  startDate: {
    type: "date",
    label: "Start Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  supervisorName: {
    type: "text",
    label: "Supervisor Name",
    placeholder: "Jane Smith",
    className: "h-11 px-4 border rounded-md",
  },
  terminationDate: {
    type: "date",
    label: "Termination Date",
    placeholder: "",
    className: "h-11 px-4 border rounded-md",
  },
  trainingProgram: {
    type: "text",
    label: "Training Program",
    placeholder: "Onboarding training",
    className: "h-11 px-4 border rounded-md",
  },
  workSchedule: {
    type: "text",
    label: "Work Schedule",
    placeholder: "9AM to 5PM, Monday to Friday",
    className: "h-11 px-4 border rounded-md",
  },
};
